<?php
/**
 * Quick fix to add missing layout_id and use_sections columns to pages table
 * Run this if you get "Undefined property: Page::$use_sections" error
 */

require_once 'config/database.php';

try {
    $pdo = new PDO("mysql:host={$config['host']};dbname={$config['database']}", 
                   $config['username'], $config['password']);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    echo "<h2>Fixing Pages Table Columns...</h2>\n";
    
    // Check if columns already exist
    $stmt = $pdo->query("DESCRIBE pages");
    $columns = $stmt->fetchAll(PDO::FETCH_COLUMN);
    
    $hasLayoutId = in_array('layout_id', $columns);
    $hasUseSections = in_array('use_sections', $columns);
    
    if (!$hasLayoutId) {
        echo "Adding layout_id column...<br>\n";
        $pdo->exec("ALTER TABLE pages ADD COLUMN layout_id INT NULL AFTER template");
        echo "✓ Added layout_id column<br>\n";
    } else {
        echo "✓ layout_id column already exists<br>\n";
    }
    
    if (!$hasUseSections) {
        echo "Adding use_sections column...<br>\n";
        $pdo->exec("ALTER TABLE pages ADD COLUMN use_sections BOOLEAN DEFAULT 0 AFTER layout_id");
        echo "✓ Added use_sections column<br>\n";
    } else {
        echo "✓ use_sections column already exists<br>\n";
    }
    
    // Add foreign key constraint if layouts table exists and constraint doesn't exist
    try {
        $stmt = $pdo->query("SHOW TABLES LIKE 'layouts'");
        if ($stmt->rowCount() > 0) {
            // Check if foreign key already exists
            $stmt = $pdo->query("
                SELECT CONSTRAINT_NAME 
                FROM information_schema.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = '{$config['database']}' 
                AND TABLE_NAME = 'pages' 
                AND COLUMN_NAME = 'layout_id' 
                AND REFERENCED_TABLE_NAME = 'layouts'
            ");
            
            if ($stmt->rowCount() == 0) {
                echo "Adding foreign key constraint...<br>\n";
                $pdo->exec("ALTER TABLE pages ADD FOREIGN KEY (layout_id) REFERENCES layouts(id) ON DELETE SET NULL");
                echo "✓ Added foreign key constraint<br>\n";
            } else {
                echo "✓ Foreign key constraint already exists<br>\n";
            }
        } else {
            echo "⚠ Layouts table not found, skipping foreign key constraint<br>\n";
        }
    } catch (Exception $e) {
        echo "⚠ Could not add foreign key constraint: " . $e->getMessage() . "<br>\n";
    }
    
    echo "<h3>✅ Pages table columns fixed successfully!</h3>\n";
    echo "<p>The 'Undefined property: Page::use_sections' error should now be resolved.</p>\n";
    
} catch (Exception $e) {
    echo "<h3>❌ Error fixing pages table:</h3>\n";
    echo "<p style='color: red;'>" . $e->getMessage() . "</p>\n";
}
?>

<!DOCTYPE html>
<html>
<head>
    <title>Fix Pages Table Columns</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 2rem auto; padding: 2rem; }
        h2, h3 { color: #333; }
        .success { color: #28a745; }
        .error { color: #dc3545; }
        .warning { color: #ffc107; }
    </style>
</head>
<body>
    <!-- Content generated by PHP above -->
    
    <h4>What was fixed:</h4>
    <ul>
        <li><strong>layout_id</strong> - INT column to link pages to custom layouts</li>
        <li><strong>use_sections</strong> - BOOLEAN column to enable modular sections</li>
        <li><strong>Foreign Key</strong> - Constraint linking layout_id to layouts table</li>
    </ul>
    
    <p><strong>Next steps:</strong></p>
    <ol>
        <li>Go back to <a href="/admin/pages">/admin/pages</a></li>
        <li>Try editing a page - the error should be gone</li>
        <li>You can now use custom layouts and enable sections for pages</li>
    </ol>
</body>
</html>
