<?php
/**
 * Test script to verify BladeEngine parentheses fix
 */

require_once 'app/core/BladeEngine.php';

// Create test directory
$testDir = 'test_views';
$cacheDir = 'test_cache';

if (!is_dir($testDir)) mkdir($testDir, 0755, true);
if (!is_dir($cacheDir)) mkdir($cacheDir, 0755, true);

// Create test blade template with problematic syntax
$testTemplate = '
<h1>Blade Engine Parentheses Test</h1>

@if(empty($items))
    <p>No items found</p>
@endif

@if(isset($user) && !empty($user->name))
    <p>Hello, {{ $user->name }}!</p>
@endif

@foreach($categories as $category)
    <div class="category">
        <h3>{{ $category->title }}</h3>
        @if(count($category->items) > 0)
            <ul>
                @foreach($category->items as $item)
                    <li>{{ $item->name }}</li>
                @endforeach
            </ul>
        @else
            <p>No items in this category</p>
        @endif
    </div>
@endforeach

@json($data)

@switch($status)
    @case("active")
        <span class="badge badge-success">Active</span>
        @break
    @case("inactive")
        <span class="badge badge-secondary">Inactive</span>
        @break
    @default
        <span class="badge badge-warning">Unknown</span>
@endswitch
';

file_put_contents($testDir . '/test.blade.php', $testTemplate);

// Initialize BladeEngine
$blade = new BladeEngine($testDir, $cacheDir);

// Test data
$testData = [
    'items' => [],
    'user' => (object)['name' => 'John Doe'],
    'categories' => [
        (object)[
            'title' => 'Electronics',
            'items' => [
                (object)['name' => 'Laptop'],
                (object)['name' => 'Phone']
            ]
        ],
        (object)[
            'title' => 'Books',
            'items' => []
        ]
    ],
    'data' => ['key' => 'value', 'nested' => ['array' => true]],
    'status' => 'active'
];

echo "<h2>Testing BladeEngine with Fixed Parentheses Handling</h2>\n";

try {
    $output = $blade->render('test', $testData);
    echo "<h3>✅ Success! Template rendered without errors:</h3>\n";
    echo "<div style='border: 1px solid #ddd; padding: 1rem; background: #f9f9f9;'>\n";
    echo $output;
    echo "</div>\n";
    
    // Show the compiled PHP code
    $cacheFile = $cacheDir . '/' . md5($testDir . '/test.blade.php') . '.php';
    if (file_exists($cacheFile)) {
        echo "<h3>Compiled PHP Code:</h3>\n";
        echo "<pre style='background: #f5f5f5; padding: 1rem; border: 1px solid #ddd; overflow-x: auto;'>\n";
        echo htmlspecialchars(file_get_contents($cacheFile));
        echo "</pre>\n";
    }
    
} catch (Exception $e) {
    echo "<h3>❌ Error:</h3>\n";
    echo "<p style='color: red;'>" . $e->getMessage() . "</p>\n";
}

// Clean up test files
unlink($testDir . '/test.blade.php');
if (file_exists($cacheDir . '/' . md5($testDir . '/test.blade.php') . '.php')) {
    unlink($cacheDir . '/' . md5($testDir . '/test.blade.php') . '.php');
}
rmdir($testDir);
rmdir($cacheDir);

echo "<h3>🎉 Test completed!</h3>\n";
echo "<p>The BladeEngine now properly handles:</p>\n";
echo "<ul>\n";
echo "<li><code>@if(empty())</code> - Functions with parentheses</li>\n";
echo "<li><code>@if(isset() && !empty())</code> - Complex conditions with multiple functions</li>\n";
echo "<li><code>@foreach(array as item)</code> - Loops with parentheses</li>\n";
echo "<li><code>@json(array)</code> - JSON encoding with nested arrays</li>\n";
echo "<li><code>@switch(variable)</code> - Switch statements</li>\n";
echo "</ul>\n";
?>

<!DOCTYPE html>
<html>
<head>
    <title>BladeEngine Parentheses Fix Test</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 2rem auto; padding: 2rem; }
        h2, h3 { color: #333; }
        code { background: #f0f0f0; padding: 0.2rem 0.4rem; border-radius: 3px; }
        pre { font-size: 0.9rem; }
        .success { color: #28a745; }
        .error { color: #dc3545; }
    </style>
</head>
<body>
    <!-- Content generated by PHP above -->
</body>
</html>
